name: GitHub Actions Vercel Preview Deployment
on:
  push:
    branches-ignore:
      - master
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm
        run: npm install
      - name: Run Unit Tests
        run: npm run test:ci