name: GitHub Actions Vercel Production Deployment
on:
  push:
    branches:
      - master
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm and Vercel CLI
        run: npm install
      - name: Run Unit Tests
        run: npm run test:ci